spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: '071369'
    url: jdbc:mysql:///vxordersystem?characterEncoding=utf-8&useSSL=false
  ###配置数据库
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    ###全局配置，如果任何一个返回给前端的对象字段为null，丢弃不显示
#  jackson:
#    default-property-inclusion: non_null
###配置访问路径项目的名称
server:
  servlet:
    context-path: /vxordersystem